### PR TITLE
Issue #2897106 by WidgetsBurritos: Skeleton capture utility

### PR DESCRIPTION
**Pull request by WidgetsBurritos**
Drupal Issue: https://www.drupal.org/node/2897106

This PR provides a skeleton capture utility that can be used when creating a new plugin.

### CODE REVIEW

**Comment by bighappyface** [comment]
Does this need to be refactored to use the `UriCaptureResponse` per #19?

**Comment by WidgetsBurritos** [comment]
@bighappyface So actually that's a good point. I included the SkeletonCaptureResponse, because I wanted to show people how to create their own response classes. But if they wish to reuse the existing one, that doesn't necessarily make sense.   Maybe we can scrap it and just leave a comment in the code telling people how to create their own response classes.   If this is truly a "skeleton" module, as we're claiming, I think the bare minimal is definitely the route to go. I'll adjust and push it up for further review.

**Comment by WidgetsBurritos** [comment]
@bighappyface Okay the change has been made. I think the comment is good enough. Work for you?

**Review by bighappyface — APPROVED** [review]
+1 for c48a848279f42f4904c7e34d153ab18c96dbb093

**Pull request merged**
